# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy_dev:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.11.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - run:
          name: Check dist
          command: ls -la dist
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
        name: Deploy to Firebase Hosting
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
    version:2
    deploy_dev:
      jobs:
        - deploy_dev:
            filters:
              branches:
                only: develop